from flask import Flask, jsonify
import random
import requests
import os

from bs4 import BeautifulSoup
app = Flask(__name__)

@app.route('/<category>', methods=['GET'])
def quotes(category):

    url = "http://www.brainyquote.com/quotes/topics/" + category + ".html"
    html = requests.get(url)
    soup = BeautifulSoup(html.text, features="html.parser")
    
    # div id of the quotes are generated by position with the format:
    # "qpos_%page%_%element%"
    # where element <- [1, .. 26] and page <- [1..] with infinite scroll
    url = "http://www.brainyquote.com/quotes/topics/" + category
    html = requests.get(url)
    soup = BeautifulSoup(html.text, features="html.parser")
    find = soup.find("div", {"id": "pos_1_" + str(random.randrange(1,60))})
    if find is not None:
        finalquote = find.find("div", {"style": "display: flex;justify-content: space-between"})
        head, sep, tail = finalquote.text.partition('<img')
        head = head.replace("\n", "")
        return jsonify({"Quote" : head})

    return jsonify({"Error":"No quotes found, Please try again or change another keyword"})

@app.route('/', methods=['GET'])
def mainPage():
    return "Welcome to Quote Generator!"

if __name__ == '__main__':
   port = int(os.environ.get("PORT", 5000))
   app.run(debug=True, port=port)